# Generated by Django 5.2.11 on 2026-02-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama (Local)'), ('gemini', 'Gemini (Google)')], default='ollama', max_length=20)),
                ('ollama_model', models.CharField(default='llama3.2-vision', help_text='Ollama model name, e.g. llama3.2-vision', max_length=100)),
                ('gemini_model', models.CharField(default='gemini-2.0-flash', help_text='Gemini model ID, e.g. gemini-2.0-flash', max_length=100)),
            ],
            options={
                'verbose_name': 'LLM Configuration',
                'verbose_name_plural': 'LLM Configuration',
            },
        ),
    ]
