# Generated by Django 5.2.11 on 2026-02-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='ocr_engine',
            field=models.CharField(choices=[('docling', 'Docling (default)'), ('tesseract', 'Tesseract (local, guj+eng)'), ('gemini_vision', 'Gemini Vision (cloud)')], default='docling', help_text='OCR engine used when processing uploaded documents', max_length=20),
        ),
    ]
