# Generated by Django 5.2.11 on 2026-02-24 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_llmconfig_ocr_engine'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('document_name', models.CharField(blank=True, max_length=500)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('message_count', models.IntegerField(default=0)),
                ('total_input_tokens', models.BigIntegerField(default=0)),
                ('total_output_tokens', models.BigIntegerField(default=0)),
                ('total_tokens', models.BigIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'Chat Session',
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('tokens_estimated', models.BooleanField(default=False, help_text='True when Ollama returned 0 tokens and chars÷4 estimation was used')),
                ('input_cost', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('output_cost', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('total_cost', models.DecimalField(decimal_places=6, default=0, max_digits=14)),
                ('response_time_seconds', models.FloatField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('ollama', 'Ollama'), ('gemini', 'Gemini')], max_length=20)),
                ('model_name', models.CharField(help_text='e.g. gemini-2.0-flash', max_length=100)),
                ('input_price_per_million', models.DecimalField(decimal_places=4, help_text='INR per 1 million input tokens', max_digits=12)),
                ('output_price_per_million', models.DecimalField(decimal_places=4, help_text='INR per 1 million output tokens', max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Model Pricing',
                'verbose_name_plural': 'Model Pricing',
                'unique_together': {('provider', 'model_name')},
            },
        ),
    ]
