# Generated by Django 5.2.11 on 2026-02-24 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatsession_chatmessage_modelpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='rag_embedding',
            field=models.CharField(choices=[('bm25', 'BM25 (keyword — English only, no cross-language)'), ('multilingual_local', 'Multilingual Local (sentence-transformers, offline)'), ('gemini_embedding', 'Gemini Multilingual Embeddings (API)')], default='multilingual_local', help_text='Embedding method for RAG mode (docs exceeding the context threshold). Multilingual options support Gujarati + English cross-language queries.', max_length=30),
        ),
    ]
