# Generated by Django 5.2.11 on 2026-02-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_llmconfig_sarvam_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=500)),
                ('markdown_path', models.CharField(blank=True, max_length=500)),
                ('json_path', models.CharField(blank=True, max_length=500)),
                ('rag_chunks_path', models.CharField(blank=True, max_length=500)),
                ('gemini_cache_name', models.CharField(blank=True, max_length=200)),
                ('total_pages', models.IntegerField(default=0)),
                ('char_count', models.IntegerField(default=0)),
                ('context_mode', models.CharField(default='full', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Document',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='provider',
            field=models.CharField(choices=[('ollama', 'Ollama (Local)'), ('gemini', 'Gemini (Google)'), ('sarvam', 'Sarvam AI')], default='ollama', max_length=20),
        ),
        migrations.AlterField(
            model_name='modelpricing',
            name='provider',
            field=models.CharField(choices=[('ollama', 'Ollama'), ('gemini', 'Gemini'), ('sarvam', 'Sarvam AI')], max_length=20),
        ),
    ]
