# Generated by Django 5.2.11 on 2026-02-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='user_email',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
