# Generated by Django 5.2.11 on 2026-03-05 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_llmconfig_use_gemini_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='source_type',
            field=models.CharField(choices=[('file', 'File Upload'), ('text', 'Pasted Text')], default='file', max_length=10),
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='ocr_engine',
            field=models.CharField(choices=[('auto', 'Auto (Docling for digital PDFs · Tesseract for scanned)'), ('docling', 'Docling (digital PDFs)'), ('tesseract', 'Tesseract (scanned · Hindi + Gujarati + English)'), ('gemini_vision', 'Gemini Vision (cloud · best quality for complex scans)')], default='docling', help_text='OCR engine used when processing uploaded documents', max_length=20),
        ),
    ]
