# Generated by Django 5.2.11 on 2026-03-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_add_agent_memory_and_agent_mode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSessionConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_name', models.BooleanField(default=True, help_text='Ask users for their name before starting a chat.')),
                ('collect_email', models.BooleanField(default=True, help_text='Ask users for their email address before starting a chat.')),
                ('verify_email', models.BooleanField(default=True, help_text="Require email OTP verification. Only applies when 'Collect email' is enabled. Disable to collect email without sending a verification code.")),
            ],
            options={
                'verbose_name': 'Chat Session Configuration',
                'verbose_name_plural': 'Chat Session Configuration',
            },
        ),
        migrations.AlterField(
            model_name='llmconfig',
            name='ocr_engine',
            field=models.CharField(choices=[('auto', 'Auto (Docling for digital PDFs · Tesseract for scanned)'), ('docling', 'Docling (digital PDFs)'), ('tesseract', 'Tesseract (scanned · Hindi + Gujarati + English)'), ('gemini_vision', 'Gemini Vision (cloud · best quality for complex scans)'), ('pdftext', 'PDF to Text (direct extraction · no OCR · fastest)')], default='docling', help_text='OCR engine used when processing uploaded documents', max_length=20),
        ),
    ]
