# Generated by Django 5.2.11 on 2026-03-08 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_chatsessionconfig_alter_llmconfig_ocr_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='qdrant_collection',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
