# Generated by Django 5.2.11 on 2026-03-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_add_qdrant_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='user_mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsessionconfig',
            name='collect_mobile',
            field=models.BooleanField(default=False, help_text='Ask users for their mobile number before starting a chat (no OTP verification).'),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='mobile',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
