# Generated by Django 5.2.11 on 2026-03-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_chatsession_user_mobile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fallback_contact', models.TextField(blank=True, default='', help_text="Contact details shown when the document doesn't contain the answer. Leave blank to use the default 'I don't know' reply. Example:\n  Gujarat Vidyapith\n  Ashram Marg, Navrangpura, Ahmedabad – 380 009\n  Phone: 079-27541148\n  Website: https://gujaratvidyapith.org/")),
            ],
            options={
                'verbose_name': 'Document Configuration',
                'verbose_name_plural': 'Document Configuration',
            },
        ),
    ]
