# Generated by Django 4.2.29 on 2026-03-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_documentconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='answer_source',
            field=models.CharField(choices=[('llm', 'LLM (normal call)'), ('session_cache', 'Session cache'), ('liked_qa', 'Liked Q&A cache')], default='llm', help_text='Where this answer was sourced from.', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='liked',
            field=models.BooleanField(blank=True, default=None, help_text='None = no feedback yet; True = thumbs up; False = thumbs down.', null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='liked_qa_qdrant_id',
            field=models.BigIntegerField(blank=True, default=None, help_text='Qdrant point ID in the liked-QA collection (populated when answer is liked).', null=True),
        ),
    ]
