# Generated by Django 4.2.29 on 2026-03-20 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0020_chatmessage_cache_feedback_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='use_session_cache',
            field=models.BooleanField(default=True, help_text='Enable per-session in-memory answer cache. When ON, repeated or similar questions within the same session are answered instantly from cache (no LLM call, zero cost). Turn OFF to always hit the LLM for every question.'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('ocr_done', 'OCR Complete (indexing pending)'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
