# Generated by Django 4.2.29 on 2026-03-20 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0021_llmconfig_use_session_cache_alter_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='rag_chunk_overlap',
            field=models.IntegerField(default=100, help_text='Character overlap between consecutive RAG chunks. Overlap ensures context at chunk boundaries is not lost. Default: 100.'),
        ),
        migrations.AddField(
            model_name='llmconfig',
            name='rag_chunk_size',
            field=models.IntegerField(default=1000, help_text='Character count per RAG chunk when splitting pasted text. Smaller values → more chunks → finer retrieval. Larger values → fewer chunks → more context per result. Default: 1000.'),
        ),
    ]
