# Generated by Django 4.2.29 on 2026-03-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0022_llmconfig_rag_chunk_overlap_llmconfig_rag_chunk_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsessionconfig',
            name='welcome_greeting',
            field=models.TextField(blank=True, default='નમસ્કાર {name}, ગૂજરાત વિદ્યાપીઠ આપનું સ્વાગત કરે છે.\n\nહું તમારો AI સહાયક છું. હું તમને ગૂજરાત વિદ્યાપીઠમાં પ્રવેશ મેળવવા બાબતે શું મદદ કરી શકું?\n\nકૃપા કરીને તમારો પ્રશ્ન નીચે જણાવો.', help_text="First message shown to the user when chat starts. Use {name} to insert the user's name (silently removed if name is not collected)."),
        ),
    ]
