# Generated by Django 4.2.29 on 2026-03-24 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0023_welcome_greeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='llmconfig',
            name='rag_top_k',
            field=models.IntegerField(default=7, help_text='Number of chunks retrieved per RAG query. Higher values provide more context but increase token cost. Default: 7.'),
        ),
    ]
