# Generated by Django 4.2.29 on 2026-04-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0025_chatmessage_nudge_answer_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='user_course',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chatsessionconfig',
            name='collect_course',
            field=models.BooleanField(default=True, help_text='Ask users for the course they are interested in.'),
        ),
        migrations.AddField(
            model_name='emailverification',
            name='course',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='documentconfig',
            name='fallback_contact',
            field=models.TextField(blank=True, default='', help_text="Contact details shown when the document doesn't contain the answer. Leave blank to use the default 'I don't know' reply. Example:\n  Gujarat Vidyapith\n  Ashram Marg, Navrangpura, Ahmedabad – 380 009\n  Website: https://gujaratvidyapith.org/"),
        ),
    ]
